/**
 * Contract addresses, ABIs, and on-chain constants for the frontend.
 *
 * Addresses are read from environment variables so they can differ between
 * local dev and production without code changes. ABIs are imported from
 * the compiled JSON artifacts in /contracts.
 *
 * All contract interactions in the app import from this file — it is the
 * single source of truth for what is deployed and where.
 */

import MealSwipeTokenJson from '../contracts/MealSwipeToken.json'
import MarketplaceJson from '../contracts/Marketplace.json'

/** On-chain address of the MealSwipeToken ERC-20 contract. */
export const TOKEN_ADDRESS  = process.env.NEXT_PUBLIC_TOKEN_ADDRESS  as `0x${string}`

/** On-chain address of the Marketplace (escrow) contract. */
export const MARKET_ADDRESS = process.env.NEXT_PUBLIC_MARKET_ADDRESS as `0x${string}`

/** On-chain address of the USDC token contract used for payments. */
export const USDC_ADDRESS   = process.env.NEXT_PUBLIC_USDC_ADDRESS   as `0x${string}`

/** Full ABI for MealSwipeToken, generated by Foundry. */
export const TOKEN_ABI  = MealSwipeTokenJson.abi

/** Full ABI for the Marketplace contract, generated by Foundry. */
export const MARKET_ABI = MarketplaceJson.abi

/**
 * Minimal USDC ABI — only the four ERC-20 functions MealCoin actually calls.
 * Using a minimal ABI avoids importing the full Circle USDC ABI and keeps
 * bundle size small. Add entries here if new USDC functions are needed.
 */
export const USDC_ABI = [
  {
    name: 'transfer',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'to', type: 'address' },
      { name: 'amount', type: 'uint256' },
    ],
    outputs: [{ name: '', type: 'bool' }],
  },
  {
    name: 'approve',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'spender', type: 'address' },
      { name: 'amount', type: 'uint256' },
    ],
    outputs: [{ name: '', type: 'bool' }],
  },
  {
    name: 'allowance',
    type: 'function',
    stateMutability: 'view',
    inputs: [
      { name: 'owner', type: 'address' },
      { name: 'spender', type: 'address' },
    ],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    name: 'balanceOf',
    type: 'function',
    stateMutability: 'view',
    inputs: [{ name: 'account', type: 'address' }],
    outputs: [{ name: '', type: 'uint256' }],
  },
] as const
